apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: kevmev/nodejs-sample-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-sample-service
spec:
  selector:
    app: nodejs-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
