pipeline {
    agent any

    environment {
        IMAGE_NAME = "kevmev/nodejs-sample-app"
        DOCKER_REGISTRY_CREDENTIALS = 'docker-hub-creds'  // tu credencial en Jenkins
    }

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('node-js-sample') {
                    script {
                        docker.build("${IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                dir('node-js-sample') {
                    withDockerRegistry([credentialsId: "${DOCKER_REGISTRY_CREDENTIALS}", url: '']) {
                        script {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('node-js-sample') {
                    // Aquí solo ejecutamos kubectl directamente, sin contenedor docker
                    sh 'kubectl apply -f K8s/deployment.yaml'
                }
            }
        }
    }
}
