pipeline {
    agent {
        docker {
        image 'lachlanevenson/k8s-kubectl' // esta imagen tiene kubectl, pero puede que necesites agregar docker client
        args '-v /var/run/docker.sock:/var/run/docker.sock' // para docker dentro del contenedor
        }
    }

    environment {
        IMAGE_NAME = "kevmev/nodejs-sample-app"
    }

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('node-js-sample') {
                    script {
                        docker.build("${IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                dir('node-js-sample') {
                    withDockerRegistry([credentialsId: 'docker-hub-creds', url: '']) {
                        script {
                            docker.image("${IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('node-js-sample') {
                    sh 'kubectl apply -f k8s/deployment.yaml'
                }
            }
        }
    }
}
